
// ล่าสุด login&Seu ยังใช้ได้ปัจจุบัน 12/03/2024






context('Login & Security ' ,() => {
    beforeEach(() => {
      cy.visit('https://pukaad.com/settings/security-and-log',{ caches: true})
      cy.viewport(1980, 1080)
  })
        describe('Email', () => {
          describe('Email หลัก',() => {
            it('Check alert กรอกเมลไม่ถูกเมลหลัก form deday',() => {
              cy.get('.ng-untouched').type('deday')
              cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
              cy.get('.ng-invalid').should('have.css', 'border-color', 'rgb(211, 47, 47)')
            })
            it('Check alert กรอกเมลไม่ถูกเมลหลัก  form deday@gmailcom',() => {
              cy.get('.ng-untouched').clear().type('deday@gmailcom')
              cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
              cy.get('.ng-invalid').should('have.css', 'border-color', 'rgb(211, 47, 47)')
            })
            it('Check alert กรอกเมลไม่ถูกเมลหลัก  form deda**ygmail.com',() => {
              cy.get('.ng-untouched').clear().type('deda**ygmail.com')
              cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
              cy.get('.ng-invalid').should('have.css', 'border-color', 'rgb(211, 47, 47)')
            })
            it('Check alert ไม่กรอกเมลหลัก  form',() => {
              cy.get('.ng-untouched').type('deay').clear()
              cy.get('.Label-Serif-medium').should('have.text',' จำเป็นต้องกรอกข้อมูล ').should('have.css','font-family','Sarabun-Regular')
              cy.get('.ng-invalid').should('have.css', 'border-color', 'rgb(211, 47, 47)')
              cy.get('.v-btn-disable').should('be.disabled')
              cy.get('.ng-invalid').should('exist')
            })
            it('Check เมลหลัก ถูกต้องและแก้',() => {
              cy.get('.ng-untouched').type('test@gmail.com')
              cy.get('.edit-btn > .Body-medium').click()
              cy.get('.Body-Serif-medium').clear().type('test12345')
              cy.get(':nth-child(1) > .fa-circle-check').should('exist')
              cy.get(':nth-child(2) > .fa-circle-check').should('exist')
              cy.get('.button-form > .v-btn').should('be.enabled')
              cy.get('.button-form > .v-btn').click()
              cy.get('.toast-message').should('have.text',' เพิ่มอีเมลสำเร็จ! ')
              cy.wait(200)
              cy.get('.toast-close-button > .ng-tns-c115-0').click()
              cy.get(':nth-child(1) > .contact-container > .contact-list > .contact-row > .contact-detail > .contact-tool > .Body-medium').click()
              cy.get('.ng-untouched').clear().type('test@gmail.com')
              cy.get('.edit-btn > .v-btn-primary').click()
            })
          })
          ////////
          describe('Email รอง',() => {
            beforeEach(() => {
              cy.get('.ng-untouched').type('test@gmail.com')
              cy.get('.edit-btn > .Body-medium').click()
              cy.get('.Body-Serif-medium').clear().type('test12345')
              cy.get(':nth-child(1) > .fa-circle-check').should('exist')
              cy.get(':nth-child(2) > .fa-circle-check').should('exist')
              cy.get('.button-form > .v-btn').should('be.enabled')
              cy.get('.button-form > .v-btn').click()
              cy.get('.toast-message').should('have.text',' เพิ่มอีเมลสำเร็จ! ')
              cy.wait(200)
              cy.get('.toast-close-button > .ng-tns-c115-0').click()
        });
            it('check font'  ,() => {
              cy.get('.Body-medium').should('have.css', 'font-family', 'Sarabun-Regular');
            });
            it('Check alert กรอกเมลไม่ถูกเมลรอง form deday',() => {
              cy.get(':nth-child(1) > .contact-container > .v-btn > .Body-medium').click()
              cy.get('.ng-untouched').type('deday')
              cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
              cy.get('.ng-invalid').should('have.css', 'border-color', 'rgb(211, 47, 47)')
            });
            it('Check alert กรอกเมลไม่ถูกเมลรอง  form deday@gmailcom',() => {
              cy.get(':nth-child(1) > .contact-container > .v-btn > .Body-medium').click()
              cy.get('.ng-untouched').clear().type('deday@gmailcom')
              cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
              cy.get('.ng-invalid').should('have.css', 'border-color', 'rgb(211, 47, 47)')
            });
            it('Check alert กรอกเมลไม่ถูกเมลรอง  form deda**ygmail.com',() => {
              cy.get(':nth-child(1) > .contact-container > .v-btn > .Body-medium').click()
              cy.get('.ng-invalid').clear().type('deda**ygmail.com')
              cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
              cy.get('.ng-invalid').should('have.css', 'border-color', 'rgb(211, 47, 47)')
            });
            it('Check alert ไม่กรอกเมลรอง  form',() => {
              cy.get(':nth-child(1) > .contact-container > .v-btn > .Body-medium').click()
              cy.get('.ng-untouched').type('deay').clear()
              cy.get('.Label-Serif-medium').should('have.text',' จำเป็นต้องกรอกข้อมูล ').should('have.css','font-family','Sarabun-Regular')
              cy.get('.ng-invalid').should('have.css', 'border-color', 'rgb(211, 47, 47)')
              cy.get('.v-btn-disable').should('be.disabled')
              cy.get('.ng-invalid').should('exist')
              cy.get('.v-btn-black').click()
            });
            it('Check เพิ่มเมลรอง ถูกต้อง + CHECK OTP',() => {
              cy.get(':nth-child(1) > .contact-container > .v-btn > .Body-medium').click()
              cy.get('.ng-untouched').type('deday@gmail.com').should('have.value','deday@gmail.com')
              cy.get('.edit-btn > .v-btn-primary').click()
              cy.get('.pass-input > .Body-medium').type('deday')
              cy.get('.button-form > .v-btn').click()
              cy.get('.m-body > .v-btn').click()
              cy.get('.authen-otp > :nth-child(1)').type('1')
              cy.get('.button-form > .v-btn').should('be.disabled')
              cy.get('.authen-otp > :nth-child(2)').type('1')
              cy.get('.button-form > .v-btn').should('be.disabled')
              cy.get('.authen-otp > :nth-child(3)').type('1')
              cy.get('.button-form > .v-btn').should('be.disabled')
              cy.get('.authen-otp > :nth-child(4)').type('1')
              cy.get('.button-form > .v-btn').should('be.disabled')
              cy.get('.authen-otp > :nth-child(5').type('1')
              cy.get('.button-form > .v-btn').should('be.disabled')
              cy.get('.authen-otp > :nth-child(6)').type('1')
              cy.get('.button-form > .v-btn').should('be.enabled')
              cy.get('.button-form > .v-btn').click()
              cy.contains('deday@gmail.com').should('exist')
              cy.get('.ng-tns-c115-1.ng-trigger > .toast-message').should('have.text',' เพิ่มอีเมลสำเร็จ! ')
              cy.wait(200)
              cy.get('.toast-close-button > .ng-tns-c115-1').click() 
            });
            it('Check สลับเมลรอง',() => {
              cy.get(':nth-child(1) > .contact-container > .v-btn > .Body-medium').click()
              cy.get('.ng-untouched').type('deday@gmail.com').should('have.value','deday@gmail.com')
              cy.get('.edit-btn > .v-btn-primary').click()
              cy.get('.pass-input > .Body-medium').type('deday')
              cy.get('.button-form > .v-btn').click()
              cy.get('.m-body > .v-btn').click()
              cy.get('.authen-otp > :nth-child(1)').type('1111111')
              cy.get('.button-form > .v-btn').click()
              cy.get('.contact-tool > :nth-child(2)').click()
              cy.get(':nth-child(1) > .contact-container > .contact-list > :nth-child(1) > .contact-detail > .contact-box > .Body-medium').should('have.text','deday@gmail.com')
              cy.get('.ng-tns-c115-2.ng-trigger > .toast-message').should('have.text',' เปลี่ยนอีเมลสำเร็จ! ')
            })
            it('Check เมลซ้ำ',() => {
              cy.get(':nth-child(1) > .contact-container > .v-btn > .Body-medium').click()
              cy.get('.ng-untouched').type('test@gmail.com').should('have.value','test@gmail.com')
              cy.get('.edit-btn > .v-btn-primary').click()
              cy.get('.Label-Serif-medium').should('have.text',' อีเมลนี้มีผู้ใช้อยู่แล้ว ').should('have.css','font-family','Sarabun-Regular')
            })
            it('Check ลบเมล',() => {
              cy.get(':nth-child(1) > .contact-container > .v-btn > .Body-medium').click()
              cy.get('.ng-untouched').type('deday@gmail.com').should('have.value','deday@gmail.com')
              cy.get('.edit-btn > .v-btn-primary').click()
              cy.get('.pass-input > .Body-medium').type('deday')
              cy.get('.button-form > .v-btn').click()
              cy.get('.m-body > .v-btn').click()
              cy.get('.authen-otp > :nth-child(1)').type('1111111')
              cy.get('.button-form > .v-btn').click()
              cy.get(':nth-child(2) > .contact-detail > .contact-tool > :nth-child(1)').click()
              cy.get('[style="display: flex; gap: 10px; width: 100%;"] > :nth-child(2)').click()
              cy.contains('devileyeg@gmail.com').should('not.exist')
              cy.get('.ng-animating > .toast-message').should('have.text',' ลบอีเมลสำเร็จ! ')
            })
          });
  
          });
          describe('รหัสผ่าน',() => {
            beforeEach(() => {
                    cy.get('.ng-untouched').type('test@gmail.com')
                    cy.get('.edit-btn > .Body-medium').click()
                    cy.get('.Body-Serif-medium').clear().type('test12345')
                    cy.get(':nth-child(1) > .fa-circle-check').should('exist')
                    cy.get(':nth-child(2) > .fa-circle-check').should('exist')
                    cy.get('.button-form > .v-btn').should('be.enabled')
                    cy.get('.button-form > .v-btn').click()
                    cy.get('.toast-message').should('have.text',' เพิ่มอีเมลสำเร็จ! ')
                    cy.wait(200)
                    cy.get('.toast-close-button > .ng-tns-c115-0').click()
                    // flow รหัสเก่า
                    cy.get('.label-with-edit > .Body-medium').click()
                    cy.get('.pass-input > .Body-medium').type('test1234').should('have.value','test1234')
                    cy.get('.fa-eye-slash').click()
                    // cy.wait(1000)
                    cy.get('.fa-eye').click()
                    // cy.wait(1000)
                    cy.get('.button-form > .v-btn').click()
              })
              it('รหัสผ่าน ใหม่ กรณี กรอกไม่ครบ 8 และ มีแค่ ตัวอักษรภาษาอังกฤษ',() => {
                cy.get('.Body-Serif-medium').type('deday')
                cy.get(':nth-child(2) > :nth-child(1) > .fa-solid').should('exist')
                cy.get(':nth-child(2) > .fa-solid').should('exist')
                cy.get('.button-form > .v-btn').should('be.disabled') 
              })
              it('รหัสผ่าน ใหม่ กรณี กรอกครบ 8 มีแค่ตัวอักษรภาษาอังกฤษ',() => {
                cy.get('.Body-Serif-medium').type('dededede')
                cy.get(':nth-child(1) > .fa-circle-check').should('exist')
                cy.get(':nth-child(2) > .fa-solid').should('exist')
                cy.get('.button-form > .v-btn').should('be.disabled') 
              })
              it('รหัสผ่าน ใหม่ กรณี กรอกไม่ครบ 8 มีตัวอักษรภาษาอังกฤษและตัวเลข',() => {
                cy.get('.Body-Serif-medium').type('deday2')
                cy.get(':nth-child(1) > :nth-child(1) > .fa-solid').should('exist')
                cy.get(':nth-child(2) > .fa-circle-check').should('exist')
                cy.get('.button-form > .v-btn').should('be.disabled') 
              })
              it('รหัสผ่าน ใหม่ กรณี พยายามกรอกเกิน 20 ตัว มีแค่ตัวอักษร',() => {
                cy.get('.Body-Serif-medium').clear().type('ddddddddddddddddddddddddddddddddddddddddddddd').should('have.value','dddddddddddddddddddd')
                cy.get(':nth-child(1) > .fa-circle-check').should('exist')
                cy.get(':nth-child(2) > .fa-solid').should('exist')
                cy.get('.button-form > .v-btn').should('be.disabled')
              })
              it('รหัสผ่าน ใหม่ ถูกฟอร์ม + check ปุ่ม ',() => {
                cy.get('.Body-Serif-medium').clear().type('test12345')
                cy.get(':nth-child(1) > .fa-circle-check').should('exist')
                cy.get(':nth-child(2) > .fa-circle-check').should('exist')
                cy.get('.button-form > .v-btn').should('be.enabled')
                cy.get('app-new-password > .m-container > .m-body > .button-form > .v-btn').click()
                cy.get('.toast-message').should('have.text',' เปลี่ยนรหัสผ่านสำเร็จ! ')
              })
            })
            describe('2FA',() => {
              it('เปิด 2FA / ปิด ',() => {
                cy.get('.v-slider').click()
                cy.get('.m-footer > .v-btn').click()
                cy.get('.ng-valid').type('111111')
                cy.get('.button-form > .v-btn').click()
                cy.get('.toast-message').should('have.text',' เปิดการยืนยันตัวตนแบบสองชั้นสำเร็จ! ')
                cy.get('.v-slider').click()
                cy.get('.pass-input > .Body-medium').type('Dedayx22222')
                cy.get('.button-form > .v-btn').click()
                cy.get('.ng-animating > .toast-message').should('have.text',' ปิดการยืนยันตัวตนแบบสองชั้นสำเร็จ! ')
              })
            })
            describe('เบอร์โทร',() => {
              describe('เบอร์โทร หลัก',() => {
                it('กรณีไม่กรอกเบอร์',() => {
                  cy.get('.contact-tool > .Body-medium').click()
                  cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .text-field-label-basic > .ng-untouched').clear()
                  cy.get('.Label-Serif-medium').should('have.text',' จำเป็นต้องกรอกข้อมูล ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .edit-btn > .v-btn-disable').should('be.disabled')
                })
                it('กรณีกรอกไม่ถูกฟอร์ม 088',() => {
                  cy.get('.contact-tool > .Body-medium').click()
                  cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .text-field-label-basic > .ng-untouched').clear().type('088')
                  cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .edit-btn > .v-btn-disable').should('be.disabled')
                })
                it('กรณีกรอกไม่ถูกฟอร์มและรูปแบบไม่ถูก ขึ้นต้นด้วย 01 02 03 04 05 07 ',() => {
                  cy.get('.contact-tool > .Body-medium').click()
                  cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .text-field-label-basic > .ng-untouched').clear().type('088')
                  cy.get('.ng-dirty').clear().type('123456789')
                  cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get('.ng-dirty').clear().type('2222222222')
                  cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get('.ng-dirty').clear().type('0130910078')
                  cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get('.ng-dirty').clear().type('0230910078')
                  cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get('.ng-dirty').clear().type('0330910078')
                  cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get('.ng-dirty').clear().type('0430910078')
                  cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get('.ng-dirty').clear().type('0530910078')
                  cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get('.ng-dirty').clear().type('0730910078')
                  cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                  cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .edit-btn > .v-btn-disable').should('be.disabled')
                })
                it('กรณีกรอกถูกฟอร์ม ทั้ง +66 66และ เบอร์ปกติ',() => {
                  cy.get('.contact-tool > .Body-medium').click()
                  cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .text-field-label-basic > .ng-untouched').clear().type('0930910078')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                  cy.get('.ng-dirty').clear().type('660930910078')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                  cy.get('.ng-dirty').clear().type('66930910078')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                  cy.get('.ng-dirty').clear().type('+660930910078')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                  cy.get('.ng-dirty').clear().type('+66930910078')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                  cy.get('.edit-btn > .v-btn-primary').click()
                  cy.get('.ng-animating > .toast-message').should('have.text',' แก้ไขเบอร์โทรศัพท์สำเร็จ! ')
                  cy.wait(200)
                  cy.get('.toast-close-button > .ng-tns-c115-0').click()
                  cy.get('.contact-box > .Body-medium').should('have.text', '(+66) 93 091 0078')
                })
              })
              describe('เบอร์โทร รอง',() => {
                it('กรณีไม่กรอกเบอร์',() => {
                  cy.get('.v-btn > .Body-medium').click()
                  cy.get(':nth-child(2) > .text-field-label-basic > .ng-untouched').type('02').clear()
                  cy.get('.Label-Serif-medium').should('have.text',' จำเป็นต้องกรอกข้อมูล ').should('have.css','font-family','Sarabun-Regular')
                  cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                })
                  it('กรณีกรอกไม่ถูกฟอร์ม 088',() => {
                    cy.get('.v-btn > .Body-medium').click()
                    cy.get(':nth-child(2) > .text-field-label-basic > .ng-untouched').clear().type('088')
                    cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                    cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .edit-btn > .v-btn-disable').should('be.disabled')
                  })
                  it('กรณีกรอกไม่ถูกฟอร์มและรูปแบบไม่ถูก ขึ้นต้นด้วย 01 02 03 04 05 07 ',() => {
                    cy.get('.v-btn > .Body-medium').click()
                    cy.get(':nth-child(2) > .text-field-label-basic > .ng-untouched').clear().type('088')
                    cy.get('.ng-dirty').clear().type('123456789')
                    cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                    cy.get('.ng-dirty').clear().type('2222222222')
                    cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                    cy.get('.ng-dirty').clear().type('0130910078')
                    cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                    cy.get('.ng-dirty').clear().type('0230910078')
                    cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                    cy.get('.ng-dirty').clear().type('0330910078')
                    cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                    cy.get('.ng-dirty').clear().type('0430910078')
                    cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                    cy.get('.ng-dirty').clear().type('0530910078')
                    cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                    cy.get('.ng-dirty').clear().type('0730910078')
                    cy.get('.Label-Serif-medium').should('have.text',' รูปแบบไม่ถูกต้อง ').should('have.css','font-family','Sarabun-Regular')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(211, 47, 47)')
                    cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .edit-btn > .v-btn-disable').should('be.disabled')
                  })
                  it('กรณีกรอกถูกฟอร์ม ทั้ง +66 66และ เบอร์ปกติ',() => {
                    cy.get('.v-btn > .Body-medium').click()
                    cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .text-field-label-basic > .ng-untouched').clear().type('0930910078')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                    cy.get('.ng-dirty').clear().type('660930910078')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                    cy.get('.ng-dirty').clear().type('66930910078')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                    cy.get('.ng-dirty').clear().type('+660930910078')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                    cy.get('.ng-dirty').clear().type('+66930910078')
                    cy.get('.ng-dirty').should('have.css', 'border-color', 'rgb(75, 156, 211)')
                    cy.get('.edit-btn > .v-btn-primary').click()
                    cy.get('.toast-message').should('have.text',' เพิ่มเบอร์โทรศัพท์สำเร็จ! ')
                    cy.wait(200)
                    cy.get('.toast-close-button > .ng-tns-c115-0').click()
                    cy.get('.contact-row.ng-star-inserted > .contact-detail > .contact-box > .Body-medium').should('have.text', '(+66) 93 091 0078')
                    it('เบอร์ซ้ำ',() => {
                      cy.get('.v-btn > .Body-medium').click()
                      cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .text-field-label-basic > .ng-untouched').type('0652009988')
                      cy.get('.v-btn-primary').click()
                      cy.get('.Label-Serif-medium').should('have.text',' เบอร์โทรศัพท์นี้มีผู้ใช้อยู่แล้ว ')
                      cy.get('.ng-dirty').clear().type('652009988')
                      cy.get('.v-btn-primary').click()
                      cy.get('.Label-Serif-medium').should('have.text',' เบอร์โทรศัพท์นี้มีผู้ใช้อยู่แล้ว ')
                      cy.get('.ng-dirty').clear().type('66652009988')
                      cy.get('.v-btn-primary').click()
                      cy.get('.Label-Serif-medium').should('have.text',' เบอร์โทรศัพท์นี้มีผู้ใช้อยู่แล้ว ')
                      cy.get('.ng-dirty').clear().type('660652009988')
                      cy.get('.v-btn-primary').click()
                      cy.get('.Label-Serif-medium').should('have.text',' เบอร์โทรศัพท์นี้มีผู้ใช้อยู่แล้ว ')
                      cy.get('.ng-dirty').clear().type('+66652009988')
                      cy.get('.v-btn-primary').click()
                      cy.get('.Label-Serif-medium').should('have.text',' เบอร์โทรศัพท์นี้มีผู้ใช้อยู่แล้ว ')
                      cy.get('.ng-dirty').clear().type('+660652009988')
                      cy.get('.v-btn-primary').click()
                      cy.get('.Label-Serif-medium').should('have.text',' เบอร์โทรศัพท์นี้มีผู้ใช้อยู่แล้ว ')
                    })
                  })
                  it('สลับเบอร์',() => {
                    cy.get('.v-btn > .Body-medium').click()
                    cy.get(':nth-child(4) > .contact-container > .contact-list > .contact-row > .text-field-label-basic > .ng-untouched').type('0930910078')
                    cy.get('.edit-btn > .v-btn-primary').click()
                    cy.get('.contact-tool > :nth-child(2)').click()
                    cy.get(':nth-child(1) > .contact-detail > .contact-box > .Body-medium').should('have.text','(+66) 93 091 0078')
                  }) 
              });
          })
        })
  